version: "3.3"

volumes:
  mariadb_volume:
    driver: local
    #mount: /home/nschumac/data/wp_database
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/nschumac/data/wp_database'
  wordpress_volume:
    driver: local
    #mount: /home/nschumac/data/wp_website 
    driver_opts:
        type: 'none'
        o: 'bind'
        device: '/home/nschumac/data/wp_website'

networks:
  yeet:

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/ 
    image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - yeet
    volumes:
      - mariadb_volume:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    ports:
      - "9000:9000"
    restart: always
    networks:
      - yeet
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/wordpress
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_MAIL=${WP_ADMIN_MAIL}
      - WP_USER=${WP_USER}
      - WP_USER_MAIL=${WP_USER_MAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_URL=${WP_URL}
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - yeet
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress