version: "3.3"

volumes:
  mariadb_volume:
  wordpress_volume:

networks:
  yeet:

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    #image: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - yeet
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress

  mariadb:
    build: ./requirements/mariadb/ 
    container_name: mariadb
    #image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - yeet
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    #image: wordpress
    ports:
      - "9000:9000"
    restart: always
    networks:
      - yeet
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - mariadb
    links:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress