version: "3.3"

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/nschumac/data/wp_database
  wordpress_volume:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: /home/nschumac/data/wp_website

networks:
  yeet:

services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    #image: nginx
    ports:
      - "443:443"
    restart: always
    networks:
      - yeet
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/wordpress

  mariadb:
    build: ./requirements/mariadb/ 
    container_name: mariadb
    #image: mariadb
    ports:
      - "3306:3306"
    restart: always
    networks:
      - yeet
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file: .env
    environment:
      - MYSQL_DATABASE=$DB_NAME
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_USER=$DB_USER
      - MYSQL_PASSWORD=$DB_PASSWORD

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    #image: wordpress
    ports:
      - "9000:9000"
    restart: always
    networks:
      - yeet
    volumes:
      - wordpress_volume:/var/www/wordpress
    depends_on:
      - mariadb
    links:
      - mariadb
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=$DB_HOST
      - WORDPRESS_DB_USER=$DB_USER
      - WORDPRESS_DB_PASSWORD=$DB_PASSWORD
      - WORDPRESS_DB_NAME=$DB_NAME